---
- name: Check if OS is supported
  include_tasks: os-support-check.yml

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS specific Snap Agent installation
  include: swisnap-{{ ansible_os_family }}.yml

- name: Include Host Agent configuration
  include: swisnap-configs.yml
