---
- name: Add repository gpg key
  apt_key:
    url: "{{ repo_gpgkey }}"
    state: present
  become: yes

- name: Set up package repository
  apt_repository:
    repo: "{{ solarwinds_snap_agent_deb_repo }}"
    state: present
  become: yes

- name: Install Snap Agent dependencies
  apt:
    name: "{{ package_name }}"
    state: latest
    update_cache: yes
  become: yes
