---
- name: Set up package repository
  yum_repository:
    name: SolarWinds_snap-agent
    file: /etc/yum.repos.d/SolarWinds_snap-agent
    description: SolarWinds Snap Agent repository
    baseurl: "{{ repo_baseurl }}"
    gpgkey: "{{ repo_gpgkey }}"
    gpgcheck: no
    repo_gpgcheck: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: "{{ repo_metadata_expire }}"
  become: yes

- name: Install Snap Agent dependencies
  yum:
    name: "{{ package_name }}"
    state: present
  become: yes
