---
- name: Restart Linux service
  service:
    name: "{{ swisnap_service }}"
    state: restarted
  become: yes

- name: Restart Windows service
  win_service:
    name: "{{ swisnap_service }}"
    state: restarted
